### ISSUE TITLE
[Bug]:   Stops working after first mini-break

### ISSUE THREAD

**Issue by philipr89** [hovancik/stretchly#1083]
### Version

- [X] I'm using version 1.9.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows Server 2012 R2 Standard

### Reproduction steps

1. Stretchly loads on Windows startup
2. After the first mini-break, it crashes with "Stretchly has stopped working".
3.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
Happens every time.

### Expected Behavior

The mini-break should complete and be set for the next break.

### Actual Behavior

The application crashes after receiving the mini-break message and countdown.

### Relevant log output

```shell
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Stretchly.exe
  Application Version:	1.9.0.0
  Application Timestamp:	619588ac
  Fault Module Name:	Stretchly.exe
  Fault Module Version:	1.9.0.0
  Fault Module Timestamp:	619588ac
  Exception Code:	c0000005
  Exception Offset:	000000000300b273
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	971d
  Additional Information 2:	971dac060c9a912a4552ce36b4f341f8
  Additional Information 3:	1f7f
  Additional Information 4:	1f7f1ba7f5ec73fa944a5f53f6a9be7e
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, can you get me the Stretchly logs? Preferences -> About -> `Ctrl+D` and there will be location of file

**Comment by philipr89** [comment]
Here they are. Thanks.

**Comment by Almedian** [comment]
Hello! My Windows 8 also crash at the same place. Dunno if it's the same bug, but I noticed, it crashes always when playing crystal sound, either after break or in settings (pressing at loudspeaker). Does not crash when I switch to tic-tac sound.

**Comment by byarbrough** [comment]
I have a similar problem, though it doesn't happen every time... best I can tell is that when I leave my computer unattended, it sometimes crashes.

**Operating System** Ubuntu 20.04.3 LTS
**Stretchly Version** `1.9.0` via Snap

```
[2022-01-17 07:39:36.024] [info]  Stretchly: initializing...
[2022-01-17 07:39:36.032] [info]  Stretchly: loading preferences
[2022-01-17 07:39:36.039] [info]  Stretchly: starting Idle time monitoring
[2022-01-17 07:39:36.040] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-01-17 07:39:37.392] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)
[2022-01-17 08:04:26.044] [info]  Stretchly: showing Mini Break notification
[2022-01-17 08:04:36.299] [info]  Stretchly: showing window 1 of 1
[2022-01-17 08:04:36.300] [info]  Stretchly: starting Mini Break
[2022-01-17 08:04:56.302] [info]  Stretchly: finishing Mini Break
[2022-01-17 08:18:44.001] [info]  Stretchly: pausing breaks because of idle time
// IT CRASHED SOMETIME HERE, AND I HAD TO RESTART IT
[2022-01-17 18:35:37.853] [info]  Stretchly: initializing...
[2022-01-17 18:35:37.861] [info]  Stretchly: loading preferences
[2022-01-17 18:35:37.868] [info]  Stretchly: starting Idle time monitoring
[2022-01-17 18:35:37.869] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-01-17 18:35:39.116] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)
[2022-01-17 19:00:27.871] [info]  Stretchly: showing Mini Break notification
[2022-01-17 19:00:38.162] [info]  Stretchly: showing window 1 of 1
[2022-01-17 19:00:38.163] [info]  Stretchly: starting Mini Break
[2022-01-17 19:00:58.165] [info]  Stretchly: finishing Mini Break
[2022-01-17 19:25:48.167] [info]  Stretchly: showing Mini Break notification
[2022-01-17 19:25:58.407] [info]  Stretchly: showing window 1 of 1
[2022-01-17 19:25:58.408] [info]  Stretchly: starting Mini Break
[2022-01-17 19:26:00.613] [info]  Stretchly: postponing Mini Break
[2022-01-17 19:27:50.590] [info]  Stretchly: showing Mini Break notification
[2022-01-17 19:28:00.816] [info]  Stretchly: showing window 1 of 1
[2022-01-17 19:28:00.816] [info]  Stretchly: starting Mini Break
[2022-01-17 19:28:20.819] [info]  Stretchly: finishing Mini Break
[2022-01-17 19:38:06.448] [info]  Stretchly: pausing breaks because of idle time
[2022-01-17 19:52:16.763] [info]  Stretchly: resuming breaks after idle time
[2022-01-17 20:15:37.771] [info]  Stretchly: pausing breaks because of idle time
// IT CRASHED SOMETIME HERE, AND I HAD TO RESTART IT
[2022-01-17 21:31:22.826] [info]  Stretchly: initializing...
[2022-01-17 21:31:22.834] [info]  Stretchly: loading preferences
[2022-01-17 21:31:22.841] [info]  Stretchly: starting Idle time monitoring
[2022-01-17 21:31:22.841] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-01-17 21:31:24.245] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)
```
[main.log](https://github.com/hovancik/stretchly/files/7885775/main.log)

**Comment by hovancik** [comment]
Thanks for the logs! There is no error here: 
```
[2022-01-17 20:15:37.771] [info]  Stretchly: pausing breaks because of idle time
// IT CRASHED SOMETIME HERE, AND I HAD TO RESTART IT
[2022-01-17 21:31:22.826] [info]  Stretchly: initializing...
```

So seems to me that something kills Stretchly when computer goes idle. Maybe some app for PC optimization or antivirus?

**Comment by hovancik** [comment]
Or I might be wrong, seeing what `c0000005` means: https://docs.microsoft.com/en-us/shows/inside/c0000005. 

I am not working with memory allocation and such, so must be then Electron

There are multiple issues with such an error in Electron https://github.com/electron/electron/search?q=c0000005&type=issues but they seem to close them without action

**Comment by byarbrough** [comment]
@hovancik it could be something killing it... 
I am on Ubuntu though, not Windows.

Let me know if there is any more information I can provide!

**Comment by hovancik** [comment]
@byarbrough there were issues in past with ubuntu and libappindicator: https://github.com/hovancik/stretchly/issues/633#issuecomment-716394124

**Comment by mixedCase** [comment]
Having the same issue using Sway, and the Waybar tray on NixOS.

Logs:

```
[2022-02-09 16:52:29.690] [info]  Stretchly: initializing...
[2022-02-09 16:52:29.700] [info]  Stretchly: loading preferences
[2022-02-09 16:52:29.705] [info]  Stretchly: starting Idle time monitoring
[2022-02-09 16:52:29.706] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-09 16:52:36.061] [info]  Stretchly: setting 'isFirstRun' to 'false' (was 'true')
[2022-02-09 16:52:45.508] [info]  Stretchly: setting 'fullscreen' to 'true' (was 'false')
[2022-02-09 16:52:54.026] [info]  Stretchly: setting 'microbreakInterval' to '1200000' (was '600000')
[2022-02-09 16:52:59.982] [info]  Stretchly: setting 'microbreakDuration' to '30000' (was '20000')
[2022-02-09 16:53:10.001] [info]  Stretchly: setting 'breakInterval' to '5' (was '2')
[2022-02-09 16:53:18.484] [info]  Stretchly: setting 'breakInterval' to '2' (was '5')
[2022-02-09 16:53:19.099] [info]  Stretchly: setting 'break' to 'false' (was 'true')
[2022-02-09 16:53:30.188] [info]  Stretchly: setting 'silentNotifications' to 'true' (was 'false')
[2022-02-09 16:53:36.602] [info]  Stretchly: setting 'checkNewVersion' to 'false' (was 'true')
[2022-02-09 16:53:53.348] [info]  Stretchly: skipping to Mini Break
[2022-02-09 16:53:53.604] [info]  Stretchly: showing window 1 of 3
[2022-02-09 16:53:53.605] [info]  Stretchly: starting Mini Break
[2022-02-09 16:53:53.610] [info]  Stretchly: showing window 2 of 3
[2022-02-09 16:53:53.622] [info]  Stretchly: showing window 3 of 3
[2022-02-09 16:54:23.606] [info]  Stretchly: finishing Mini Break
[2022-02-09 16:54:46.965] [info]  Stretchly: initializing...
[2022-02-09 16:54:46.971] [info]  Stretchly: loading preferences
[2022-02-09 16:54:46.976] [info]  Stretchly: starting Idle time monitoring
[2022-02-09 16:54:46.976] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-09 17:14:36.978] [info]  Stretchly: showing Mini Break notification
[2022-02-09 17:14:47.157] [info]  Stretchly: showing window 1 of 3
[2022-02-09 17:14:47.158] [info]  Stretchly: starting Mini Break
[2022-02-09 17:14:47.158] [error] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at WriteStream.Socket._writeGeneric (node:net:795:11)
    at WriteStream.Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at WriteStream.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.log (node:internal/console/constructor:359:26)
    at consoleLog (/nix/store/cxcm7r7q1821yax97kbq3254q9cmnbrk-stretchly-1.8.1/share/stretchly/app.asar/node_modules/electron-log/src/transports/console.js:100:17)
[2022-02-09 17:14:47.171] [info]  Stretchly: showing window 2 of 3
[2022-02-09 17:14:47.172] [error] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at WriteStream.Socket._writeGeneric (node:net:795:11)
    at WriteStream.Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at WriteStream.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.log (node:internal/console/constructor:359:26)
    at consoleLog (/nix/store/cxcm7r7q1821yax97kbq3254q9cmnbrk-stretchly-1.8.1/share/stretchly/app.asar/node_modules/electron-log/src/transports/console.js:100:17)
[2022-02-09 17:14:47.201] [info]  Stretchly: showing window 3 of 3
[2022-02-09 17:14:47.202] [error] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at WriteStream.Socket._writeGeneric (node:net:795:11)
    at WriteStream.Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at WriteStream.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.log (node:internal/console/constructor:359:26)
    at consoleLog (/nix/store/cxcm7r7q1821yax97kbq3254q9cmnbrk-stretchly-1.8.1/share/stretchly/app.asar/node_modules/electron-log/src/transports/console.js:100:17)
[2022-02-09 17:15:17.160] [info]  Stretchly: finishing Mini Break
[2022-02-09 17:15:17.165] [error] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at WriteStream.Socket._writeGeneric (node:net:795:11)
    at WriteStream.Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at WriteStream.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.log (node:internal/console/constructor:359:26)
    at consoleLog (/nix/store/cxcm7r7q1821yax97kbq3254q9cmnbrk-stretchly-1.8.1/share/stretchly/app.asar/node_modules/electron-log/src/transports/console.js:100:17)
[2022-02-10 18:48:34.412] [info]  Stretchly: initializing...
[2022-02-10 18:48:34.418] [info]  Stretchly: loading preferences
[2022-02-10 18:48:34.423] [info]  Stretchly: starting Idle time monitoring
[2022-02-10 18:48:34.424] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-10 18:48:49.504] [info]  Stretchly: skipping to Mini Break
[2022-02-10 18:48:49.760] [info]  Stretchly: showing window 1 of 3
[2022-02-10 18:48:49.760] [info]  Stretchly: starting Mini Break
[2022-02-10 18:48:49.761] [error] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at WriteStream.Socket._writeGeneric (node:net:795:11)
    at WriteStream.Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at WriteStream.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.log (node:internal/console/constructor:359:26)
    at consoleLog (/nix/store/cxcm7r7q1821yax97kbq3254q9cmnbrk-stretchly-1.8.1/share/stretchly/app.asar/node_modules/electron-log/src/transports/console.js:100:17)
[2022-02-10 18:48:49.779] [info]  Stretchly: showing window 2 of 3
[2022-02-10 18:48:49.780] [error] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at WriteStream.Socket._writeGeneric (node:net:795:11)
    at WriteStream.Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at WriteStream.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.log (node:internal/console/constructor:359:26)
    at consoleLog (/nix/store/cxcm7r7q1821yax97kbq3254q9cmnbrk-stretchly-1.8.1/share/stretchly/app.asar/node_modules/electron-log/src/transports/console.js:100:17)
[2022-02-10 18:48:49.790] [info]  Stretchly: showing window 3 of 3
[2022-02-10 18:48:49.791] [error] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at WriteStream.Socket._writeGeneric (node:net:795:11)
    at WriteStream.Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at WriteStream.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.log (node:internal/console/constructor:359:26)
    at consoleLog (/nix/store/cxcm7r7q1821yax97kbq3254q9cmnbrk-stretchly-1.8.1/share/stretchly/app.asar/node_modules/electron-log/src/transports/console.js:100:17)
[2022-02-10 18:49:19.762] [info]  Stretchly: finishing Mini Break
[2022-02-10 18:49:19.767] [error] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at WriteStream.Socket._writeGeneric (node:net:795:11)
    at WriteStream.Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at WriteStream.Writable.write (node:internal/streams/writable:334:10)
    at console.value (node:internal/console/constructor:285:16)
    at console.log (node:internal/console/constructor:359:26)
    at consoleLog (/nix/store/cxcm7r7q1821yax97kbq3254q9cmnbrk-stretchly-1.8.1/share/stretchly/app.asar/node_modules/electron-log/src/transports/console.js:100:17)
[2022-02-10 18:50:24.360] [info]  Stretchly: initializing...
[2022-02-10 18:50:24.366] [info]  Stretchly: loading preferences
[2022-02-10 18:50:24.371] [info]  Stretchly: starting Idle time monitoring
[2022-02-10 18:50:24.372] [info]  Stretchly: starting Do Not Disturb monitoring
```

**Comment by hovancik** [comment]
That's rather strange error ;/ Tried googling around but haven't found anything useful.

@mixedCase any chance you could test in another DE?

**Comment by mixedCase** [comment]
@hovancik it's the only compositor I run I'm afraid. It's not a full DE, so there's very little that can go wrong.
The tray I use is libappindicator-compatible FWIW.

Is there any way to up the verbosity to try to get better logs?

**Comment by hovancik** [comment]
some people used `dgb` https://github.com/hovancik/stretchly/issues/633#issuecomment-687633349

**Comment by hovancik** [comment]
is this still issue? I'll close and can reopen if this still persists with the latest version.

**Comment by philipr89** [comment]
It is no longer an issue. Thanks.
