### ISSUE TITLE
[Bug]:  timeToBreakInTray causes crash in Stretchly 1.10.0 on macOS

### ISSUE THREAD

**Issue by chchen2021** [hovancik/stretchly#1104]
### Version

- [X] I'm using version 1.9.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.2.1

### Reproduction steps

1. Upgrade to Stretchly 1.10.0
2. Change config.json to `"timeToBreakInTray": true`
3. Skip to the next mini or long break
4. Stretchly crashes and exits at this moment

When I revert back to 1.9.0, everything behaves normally. In 1.10.0, the above sequence always leads to a crash. 

### Expected Behavior

Smooth operation without any crash, as in 1.9.0.

### Actual Behavior

App crash upon each skip to a break with `"timeToBreakInTray": true`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Could you please paste the logs?

**Comment by chchen2021** [comment]
[2022-02-24 06:11:56.554] [info]  Stretchly: initializing...
[2022-02-24 06:11:56.561] [info]  Stretchly: loading preferences
[2022-02-24 06:11:56.567] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-24 06:12:04.814] [info]  Stretchly: skipping to Mini Break
[2022-02-24 06:12:05.183] [info]  Stretchly: showing window 1 of 1
[2022-02-24 06:12:05.187] [info]  Stretchly: starting Mini Break
[2022-02-24 06:12:10.478] [info]  Stretchly: postponing Mini Break
[2022-02-24 06:14:05.521] [info]  Stretchly: initializing...
[2022-02-24 06:14:05.529] [info]  Stretchly: loading preferences
[2022-02-24 06:14:05.536] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-24 06:14:14.863] [error] Error: Failed to load image from path '/Applications/Stretchly.app/Contents/Resources/app.asar/images/app-icons/trayMacMonochromeNumberNaNTemplate.png'
    at updateTray (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1083:11)
    at BreaksPlanner.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:184:7)
    at BreaksPlanner.emit (node:events:390:28)
    at BreaksPlanner.skipToMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/breaksPlanner.js:183:10)
    at skipToMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:966:18)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)
[2022-02-24 06:14:15.565] [error] Error: Failed to load image from path '/Applications/Stretchly.app/Contents/Resources/app.asar/images/app-icons/trayMacMonochromeNumberNaNTemplate.png'
    at Timeout.updateTray [as _onTimeout] (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1083:11)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
    at messageBox (node:electron/js2c/browser_init:49:4672)
    at Object.showMessageBox (node:electron/js2c/browser_init:49:5487)
    at process.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:20:10)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
[2022-02-24 06:14:25.565] [error] Error: Failed to load image from path '/Applications/Stretchly.app/Contents/Resources/app.asar/images/app-icons/trayMacMonochromeNumberNaNTemplate.png'
    at Timeout.updateTray [as _onTimeout] (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1083:11)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
    at messageBox (node:electron/js2c/browser_init:49:4672)
    at Object.showMessageBox (node:electron/js2c/browser_init:49:5487)
    at process.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:20:10)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
[2022-02-24 06:14:31.003] [info]  Stretchly: showing window 1 of 1
[2022-02-24 06:14:31.028] [info]  Stretchly: starting Mini Break
[2022-02-24 06:14:35.931] [info]  Stretchly: finishing Mini Break
[2022-02-24 06:15:06.393] [error] Error: Failed to load image from path '/Applications/Stretchly.app/Contents/Resources/app.asar/images/app-icons/trayMacMonochromeNumberNaNTemplate.png'
    at updateTray (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1083:11)
    at BreaksPlanner.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:184:7)
    at BreaksPlanner.emit (node:events:390:28)
    at BreaksPlanner.skipToMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/breaksPlanner.js:183:10)
    at skipToMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:966:18)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)
[2022-02-24 06:15:08.857] [info]  Stretchly: showing window 1 of 1
[2022-02-24 06:15:08.867] [info]  Stretchly: starting Mini Break
[2022-02-24 06:15:15.270] [info]  Stretchly: postponing Mini Break
[2022-02-24 06:15:45.266] [info]  Stretchly: showing Mini Break notification
[2022-02-24 06:16:15.540] [info]  Stretchly: showing window 1 of 1
[2022-02-24 06:16:15.544] [info]  Stretchly: starting Mini Break
[2022-02-24 06:16:30.984] [info]  Stretchly: finishing Mini Break
[2022-02-24 06:16:47.478] [error] Error: Failed to load image from path '/Applications/Stretchly.app/Contents/Resources/app.asar/images/app-icons/trayMacMonochromeNumberNaNTemplate.png'
    at updateTray (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1083:11)
    at BreaksPlanner.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:184:7)
    at BreaksPlanner.emit (node:events:390:28)
    at BreaksPlanner.skipToMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/breaksPlanner.js:183:10)
    at skipToMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:966:18)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)
[2022-02-24 06:16:52.581] [error] Error: Failed to load image from path '/Applications/Stretchly.app/Contents/Resources/app.asar/images/app-icons/trayMacMonochromeNumberNaNTemplate.png'
    at Timeout.updateTray [as _onTimeout] (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1083:11)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
    at messageBox (node:electron/js2c/browser_init:49:4672)
    at Object.showMessageBox (node:electron/js2c/browser_init:49:5487)
    at process.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:20:10)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
[2022-02-24 06:16:59.581] [info]  Stretchly: showing window 1 of 1
[2022-02-24 06:16:59.592] [info]  Stretchly: starting Mini Break
[2022-02-24 06:17:16.577] [info]  Stretchly: finishing Mini Break
[2022-02-24 06:18:29.282] [info]  Stretchly: initializing...
[2022-02-24 06:18:29.291] [info]  Stretchly: loading preferences
[2022-02-24 06:18:29.302] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-24 06:19:41.580] [info]  Stretchly: initializing...
[2022-02-24 06:19:41.587] [info]  Stretchly: loading preferences
[2022-02-24 06:19:41.593] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-24 06:20:21.038] [info]  Stretchly: skipping to Mini Break
[2022-02-24 06:20:21.416] [info]  Stretchly: showing window 1 of 1
[2022-02-24 06:20:21.420] [info]  Stretchly: starting Mini Break
[2022-02-24 06:20:25.111] [info]  Stretchly: postponing Mini Break
[2022-02-24 06:20:32.842] [info]  Stretchly: skipping to Mini Break
[2022-02-24 06:20:33.211] [info]  Stretchly: showing window 1 of 1
[2022-02-24 06:20:33.215] [info]  Stretchly: starting Mini Break
[2022-02-24 06:20:36.973] [info]  Stretchly: finishing Mini Break

**Comment by chchen2021** [comment]
Stretchly 1.9.0 at the beginning and end, 1.10.0 in the middle. 

In 1.10.0, when skipping to break,  the break would take place a few seconds after clicking OK on the error message: "An error occurred while running Stretchly and it will now quit. To report the issue, click Report." However, I could not quit Stretchly at all and the error message would persist with each skip to break. I logged out of macOS and logged back in, now I could quit Stretchly and reinstall 1.9.0. Stretchly worked fine as soon as this earlier version was installed.

**Comment by lucascosti** [comment]
I'm seeing the same behaviour on MacOS 12.2.1:

```
[2022-03-03 12:25:36.643] [info]  Stretchly: initializing...
[2022-03-03 12:25:36.650] [info]  Stretchly: loading preferences
[2022-03-03 12:25:36.659] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-03-03 12:25:46.733] [error] Error: Failed to load image from path '/Applications/Stretchly.app/Contents/Resources/app.asar/images/app-icons/trayMacMonochromeNumberNaNTemplate.png'
    at updateTray (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1083:11)
    at BreaksPlanner.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:184:7)
    at BreaksPlanner.emit (node:events:390:28)
    at BreaksPlanner.skipToMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/breaksPlanner.js:183:10)
    at skipToMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:966:18)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)
[2022-03-03 12:25:46.789] [error] Error: Failed to load image from path '/Applications/Stretchly.app/Contents/Resources/app.asar/images/app-icons/trayMacMonochromeNumberNaNTemplate.png'
    at Timeout.updateTray [as _onTimeout] (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1083:11)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
    at messageBox (node:electron/js2c/browser_init:49:4672)
    at Object.showMessageBox (node:electron/js2c/browser_init:49:5487)
    at process.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:20:10)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
```
