### ISSUE TITLE
[Bug]:   Stretchly crashes every time I use the "skip to the next" tray menu item

### ISSUE THREAD

**Issue by gregsanto** [hovancik/stretchly#1178]
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Reproduction steps

This is 100% reproducible for me by taking the following steps at any time when there is no active break window:

1. Right click on the Stretchly tray icon
2. Mouse over the "skip to the next" menu item
3. Select either the "mini break" or "long break" submenu items

### Expected Behavior

The appropriate mini break or long break window should pop up.

### Actual Behavior

The appropriate mini break or long break window pops up, along with the following error dialog box (see below). The break window continues counting down until I click okay on the dialog box. Once the dialog box is closed Stretchly closes as well.

![image](https://user-images.githubusercontent.com/53320353/181115457-736af798-bd8a-46ca-8ef3-4e5572a60c40.png)

### Relevant log output

```shell
[2022-07-26 14:23:41.703] [info]  Stretchly: initializing...
[2022-07-26 14:23:41.712] [info]  Stretchly: loading preferences
[2022-07-26 14:23:41.723] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-07-26 14:23:41.725] [info]  Stretchly: starting App exclusions monitoring
[2022-07-26 14:23:41.850] [info]  Stretchly: resumeBreaksShortcut registration successful (CommandOrControl+Shift+F12)
[2022-07-26 14:23:41.852] [info]  Stretchly: pauseBreaksShortcut registration successful (CommandOrControl+F12)
[2022-07-26 14:23:43.612] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-07-26 14:23:56.970] [error] Error: Failed to load image from path 'C:\Users\me\AppData\Local\Programs\stretchly\resources\app.asar\images\app-icons\trayMonochromeInvertedNumberNaN.png'
    at updateTray (C:\Users\me\AppData\Local\Programs\stretchly\resources\app.asar\main.js:1083:11)
    at BreaksPlanner.<anonymous> (C:\Users\me\AppData\Local\Programs\stretchly\resources\app.asar\main.js:184:7)
    at BreaksPlanner.emit (node:events:390:28)
    at BreaksPlanner.skipToMicrobreak (C:\Users\me\AppData\Local\Programs\stretchly\resources\app.asar\breaksPlanner.js:183:10)
    at skipToMicrobreak (C:\Users\me\AppData\Local\Programs\stretchly\resources\app.asar\main.js:966:18)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)
[2022-07-26 14:23:57.500] [info]  Stretchly: showing window 1 of 1
[2022-07-26 14:23:57.503] [info]  Stretchly: starting Mini Break
[2022-07-26 14:23:58.968] [info]  Stretchly: postponing Mini Break
```

### Preferences

```shell
{
	"microbreakDuration": 60000,
	"microbreakInterval": 240000,
	"breakDuration": 600000,
	"breakInterval": 3,
	"breakNotification": false,
	"microbreakNotification": false,
	"breakNotificationInterval": 30000,
	"microbreakNotificationInterval": 10000,
	"microbreak": true,
	"break": true,
	"microbreakStrictMode": true,
	"breakStrictMode": true,
	"morningHour": 6,
	"microbreakPostpone": true,
	"breakPostpone": true,
	"microbreakPostponeTime": 60000,
	"breakPostponeTime": 60000,
	"microbreakPostponesLimit": 1,
	"microbreakPostponableDurationPercent": 100,
	"breakPostponesLimit": 1,
	"breakPostponableDurationPercent": 100,
	"mainColor": "#1D1F21",
	"transparentMode": false,
	"opacity": 0.9,
	"audio": "silence",
	"volume": 1,
	"fullscreen": false,
	"ideas": true,
	"naturalBreaks": false,
	"naturalBreaksInactivityResetTime": 300000,
	"allScreens": false,
	"useIdeasFromSettings": true,
	"language": "en",
	"notifyNewVersion": false,
	"isFirstRun": false,
	"posLatitude": 0,
	"posLongitude": 0,
	"useMonochromeTrayIcon": true,
	"useMonochromeInvertedTrayIcon": true,
	"silentNotifications": true,
	"monitorDnd": true,
	"microbreakStartSoundPlaying": false,
	"breakStartSoundPlaying": false,
	"themeSource": "system",
	"endBreakShortcut": "CmdOrCtrl+X",
	"breakWindowWidth": 0.85,
	"breakWindowHeight": 0.85,
	"checkNewVersion": false,
	"breakIdeas": [
		{
			"data": [
				"",
				"Stretch hamstrings"
			],
			"enabled": true
		},
		{
			"data": [
				"",
				"Stretch quads"
			],
			"enabled": true
		},
		{
			"data": [
				"",
				"Stretch hip flexors"
			],
			"enabled": true
		},
		{
			"data": [
				"",
				"Stretch calves"
			],
			"enabled": true
		},
		{
			"data": [
				"",
				"Stretch lower back"
			],
			"enabled": true
		},
		{
			"data": [
				"",
				"Stretch hamstrings"
			],
			"enabled": true
		}
	],
	"microbreakIdeas": [
		{
			"data": "Do not skip this break!",
			"enabled": true
		}
	],
	"showBreaksAsRegularWindows": false,
	"appExclusions": [
		{
			"rule": "pause",
			"active": true,
			"commands": [
				"CptHost.exe"
			]
		}
	],
	"appExclusionsCheckInterval": 1000,
	"pauseForSuspendOrLock": true,
	"pauseBreaksShortcut": "CommandOrControl+F12",
	"resumeBreaksShortcut": "CommandOrControl+Shift+F12",
	"screen": "primary",
	"timeToBreakInTray": true,
	"currentTimeInBreaks": false
}
```

### Additional information

```shell
It appears the issue is that the program is trying to load a numbered tray icon image but the number is invalid (NaN).
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi and thanks for the report! This should be fixed in new version: https://github.com/hovancik/stretchly/pull/1107
