### ISSUE TITLE
[Bug]: Cannot Open Stretchly 1.13.0 on Windows 10

### ISSUE THREAD

**Issue by Glinte** [hovancik/stretchly#1253]
### Version

- [X] I'm using version 1.13.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### Reproduction steps

1. Download Stretchly-Setup-1.13.0.exe
2. Run the installer, issue occurs for both install for all users and install for me 
3. Finish setup
4. Open Stretchly
5. Error Message Shows Up
...
**Reproduces how often:** 100%

### Expected Behavior

No error

### Actual Behavior

Error window
![image](https://user-images.githubusercontent.com/96855131/209346426-83a6dc7e-b9b9-49ab-8ffd-0f10dbaf92a7.png)

### Relevant log output

```shell
[2022-12-23 21:44:42.513] [info]  Stretchly: initializing...
[2022-12-23 21:44:42.522] [info]  Stretchly: migrating preferences from Stretchly v0.0.0 to v1.13.0
[2022-12-23 21:44:42.525] [error] Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. TypeError: Use `delete()` to clear values
    at ElectronStore._migrate (C:\Users\ACER\AppData\Local\Programs\Stretchly\resources\app.asar\node_modules\conf\dist\source\index.js:429:23)
    at new Conf (C:\Users\ACER\AppData\Local\Programs\Stretchly\resources\app.asar\node_modules\conf\dist\source\index.js:150:18)
    at new ElectronStore (C:\Users\ACER\AppData\Local\Programs\Stretchly\resources\app.asar\node_modules\electron-store\index.js:69:3)
    at App.initialize (C:\Users\ACER\AppData\Local\Programs\Stretchly\resources\app.asar\main.js:167:16)
    at App.emit (node:events:513:28)
```

### Additional information

```shell
This is my first installation of Stretchly
Also, Stretchly 1.12.0 installs and runs successfully.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, I guess this is because it's first install. If you install 1.12 and then 1.13, it should work ok :) can you try?

**Comment by hovancik** [comment]
I wrote a quick fix, so next version will have this :)

**Comment by Glinte** [comment]
Insomnia update: yeah installing 1.12 and then 1.13 works. Thanks for the quick response!

**Comment by hovancik** [comment]
Glad to hear that, hope you'll enjoy Stretchly!

**Comment by joydashy** [comment]
I had the same issue on Windows 11 and installing 1.12 also resolved it. But that still makes it a bug right? Bit odd that 1.13 is not standalone?

**Comment by joydashy** [comment]
Also just installed on a 2nd Win11 machine, and 1.12 needs to be run after install, then install and run 1.13. Only installing 1.12 is not sufficient.

**Comment by hovancik** [comment]
Ah, okay :)  I am just making new release 1.13.1 that should fix that, so fingers crossed :)
