### ISSUE TITLE
[Bug]:   RPM package is not installable on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by mark-raymond** [hovancik/stretchly#1266]
### Version

- [X] I'm using version 1.13.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

openSUSE Tumbleweed (uname -a: Linux mdr-lafite 6.1.7-1-default #1 SMP PREEMPT_DYNAMIC Wed Jan 18 11:12:34 UTC 2023 (872045c) x86_64 x86_64 x86_64 GNU/Linux)

### Reproduction steps

1. Attempt to install the rpm package. The install cannot proceed due to `libuuid` not being a package that exists in openSUSE Tumbleweed.
```
$ sudo zypper install /tmp/Stretchly-1.13.1.x86_64.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libuuid' needed by the to be installed Stretchly-1.13.1-1.x86_64
 Solution 1: do not install Stretchly-1.13.1-1.x86_64
 Solution 2: break Stretchly-1.13.1-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): c
```

There is a package `libuuid1`; I don't know if the dependencies should be updated to point at that instead?

### Expected Behavior

Package to be installed.

### Actual Behavior

Package cannot be installed due to unavailable dependencies.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Looks like issue with electron. People seems to have been able to workaround this: https://github.com/jgraph/drawio-desktop/issues/493#issuecomment-1185954309

Would you be able to test the solution? Possibly create a PR?

**Comment by mark-raymond** [comment]
Just tried to build the rpm from latest trunk, but was unable to. I ran things in docker (using [this image](https://hub.docker.com/layers/library/node/16.17.1/images/sha256-674750127bbf45f52660ada71ed1f1491d15e94c16583bff6df0df2489481049)). `npm install --no-save` worked fine and `npm run pack` worked fine but `npm run dist` failed:
```
node@578f5cea3a67:/stretchly$ npm run dist

> Stretchly@1.13.1 dist
> electron-builder build --x64 --ia32

  • electron-builder  version=23.6.0 os=6.1.7-1-default
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=macos-notification-state@2.0.2, windows-focus-assist@1.3.0, windows-notification-state@2.0.0, windows-quiet-hours@1.2.7, macos-notification-state@1.3.6, windows-notification-state@1.3.4
                                    platform=linux
                                    arch=x64
  • packaging       platform=linux arch=x64 electron=22.0.0 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/Stretchly-1.13.1.AppImage
  • building        target=tar.xz arch=x64 file=dist/Stretchly-1.13.1.tar.xz
  • rebuilding native dependencies  dependencies=macos-notification-state@2.0.2, windows-focus-assist@1.3.0, windows-notification-state@2.0.0, windows-quiet-hours@1.2.7, macos-notification-state@1.3.6, windows-notification-state@1.3.4
                                    platform=linux
                                    arch=ia32
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path /stretchly/app/node_modules/@meetfranz/electron-notification-state/node_modules/macos-notification-state
    npm ERR! command failed
    npm ERR! command sh /tmp/install-6e0be687.sh
    npm ERR! make: Entering directory '/stretchly/app/node_modules/@meetfranz/electron-notification-state/node_modules/macos-notification-state/build'
    npm ERR!   CXX(target) Release/obj.target/notificationstate/lib/notificationstate.o
    npm ERR! make: Leaving directory '/stretchly/app/node_modules/@meetfranz/electron-notification-state/node_modules/macos-notification-state/build'
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.17.1 | linux | x64
    npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/stretchly/app/node_modules/@meetfranz/electron-notification-state/node_modules/macos-notification-state/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/node/.electron-gyp/22.0.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/node/.electron-gyp/22.0.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/node/.electron-gyp/22.0.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/stretchly/app/node_modules/@meetfranz/electron-notification-state/node_modules/macos-notification-state',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info spawn make
    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    npm ERR! In file included from /usr/lib/gcc/x86_64-linux-gnu/8/include/stdint.h:9,
    npm ERR!                  from /home/node/.electron-gyp/22.0.0/include/node/js_native_api_types.h:8,
    npm ERR!                  from /home/node/.electron-gyp/22.0.0/include/node/js_native_api.h:24,
    npm ERR!                  from /home/node/.electron-gyp/22.0.0/include/node/node_api.h:12,
    npm ERR!                  from ../lib/notificationstate.cc:2:
    npm ERR! /usr/include/stdint.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
    npm ERR!  #include <bits/libc-header-start.h>
    npm ERR!           ^~~~~~~~~~~~~~~~~~~~~~~~~~
    npm ERR! compilation terminated.
    npm ERR! make: *** [notificationstate.target.mk:115: Release/obj.target/notificationstate/lib/notificationstate.o] Error 1
    npm ERR! gyp ERR! build error 
    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Linux 6.1.7-1-default
    npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd /stretchly/app/node_modules/@meetfranz/electron-notification-state/node_modules/macos-notification-state
    npm ERR! gyp ERR! node -v v16.17.1
    npm ERR! gyp ERR! node-gyp -v v9.0.0
    npm ERR! gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/node/.npm/_logs/2023-01-25T20_36_34_910Z-debug-0.log
    
                    command=/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js rebuild macos-notification-state@2.0.2 windows-focus-assist@1.3.0 windows-notification-state@2.0.0 windows-quiet-hours@1.2.7 macos-notification-state@1.3.6 windows-notification-state@1.3.4
                    workingDir=
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=954ms
  • building        target=deb arch=x64 file=dist/Stretchly_1.13.1_amd64.deb
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z size=5.0 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=1.041s
  ⨯ cannot execute  cause=exit status 1
                    out={:timestamp=>"2023-01-25T20:37:46.611551+0000", :message=>"No such file (for after_install): \"/tmp/t-fSMOvd/0-after-install\"", :level=>:error}

                    errorOut=/home/node/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/command.rb:444:in `read': No such file or directory @ rb_sysopen - /tmp/t-fSMOvd/0-after-install (Errno::ENOENT)
        from /home/node/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/command.rb:444:in `block in execute'
        from /home/node/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/command.rb:448:in `execute'
        from /home/node/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/vendor/ruby/2.3.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /home/node/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/lib/fpm/command.rb:574:in `run'
        from /home/node/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/vendor/ruby/2.3.0/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
        from /home/node/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/app/bin/fpm:7:in `<main>'
    
                    command=/home/node/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir --force -t deb -d libgtk-3-0 -d libnotify4 -d libnss3 -d libxss1 -d libxtst6 -d xdg-utils -d libatspi2.0-0 -d libuuid1 -d libsecret-1-0 --deb-recommends libappindicator3-1 --deb-compression xz --architecture amd64 --after-install /tmp/t-fSMOvd/0-after-install --after-remove /tmp/t-fSMOvd/1-after-remove --description '
     The break time reminder app' --version 1.13.1 --package /stretchly/dist/Stretchly_1.13.1_amd64.deb --name Stretchly --maintainer 'Jan Hovancik <jan@hovancik.net>' --url https://hovancik.net/stretchly --vendor 'Jan Hovancik <jan@hovancik.net>' --deb-priority optional --license BSD-2-Clause /stretchly/dist/linux-unpacked/=/opt/Stretchly /stretchly/dist/.icon-set/icon_16x16.png=/usr/share/icons/hicolor/16x16/apps/stretchly.png /stretchly/dist/.icon-set/icon_32.png=/usr/share/icons/hicolor/32x32/apps/stretchly.png /stretchly/dist/.icon-set/icon_48x48.png=/usr/share/icons/hicolor/48x48/apps/stretchly.png /stretchly/dist/.icon-set/icon_64.png=/usr/share/icons/hicolor/64x64/apps/stretchly.png /stretchly/dist/.icon-set/icon_128.png=/usr/share/icons/hicolor/128x128/apps/stretchly.png /stretchly/dist/.icon-set/icon_256.png=/usr/share/icons/hicolor/256x256/apps/stretchly.png /stretchly/dist/.icon-set/icon_512.png=/usr/share/icons/hicolor/512x512/apps/stretchly.png /stretchly/dist/.icon-set/icon_1024.png=/usr/share/icons/hicolor/1024x1024/apps/stretchly.png /tmp/t-Ax6gNL/b-Stretchly.desktop=/usr/share/applications/stretchly.desktop
                    workingDir=
```
Log file here: [2023-01-25T20_36_34_910Z-debug-0.log](https://github.com/hovancik/stretchly/files/10503537/2023-01-25T20_36_34_910Z-debug-0.log)

**Comment by hovancik** [comment]
Can you try running this, so we only build rpm? 

`node_modules/.bin/electron-builder build --x64 --linux rpm`

**Comment by mark-raymond** [comment]
Thanks. I've now been able to build the rpm package.

I don't think the fix in that link is appropriate. While it does make the package installable, it removes several things from the dependencies list that probably want to be there.

`rpm -qpR` with the unmodified package:
```
/bin/sh
/bin/sh
at-spi2-core
gtk3
libXScrnSaver
libXtst
libnotify
libuuid
nss
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
xdg-utils
```

`rpm -qpR` with the modified package:
```
/bin/sh
/bin/sh
/usr/lib64/libuuid.so.1
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

All we really want to do is replace `libuuid` with `libuuid1`, not remove almost all the other dependencies.

**Comment by hovancik** [comment]
Yeah doesn't look correctly. I guess that's because we set 

```
      "depends":[
        "/usr/lib64/libuuid.so.1"
      ]
```

thus removing some dependencies set by `electron-builder`? I've tried to find a way to not replace the `depends` but to add to it but no success. What could work would be to respecify everything.

**Comment by mark-raymond** [comment]
Things I have found in occasional looking at this again:

- The default dependencies come from [app-builder](https://github.com/develar/app-builder) in [fmp.go](https://github.com/develar/app-builder/blob/master/pkg/package-format/fpm/fpm.go).
- electron-builder is not updating app-builder due to electron-userland/electron-builder#6684, with corresponding app-builder issue https://github.com/develar/app-builder#83, so fixing upstream in app-builder is unlikely to solve things quickly.
- The dependency that works on both Fedora and openSUSE, for both amd64 and arm64, is `libuuid.so.1()(64bit)`. (For some reason, specifying the path `/usr/lib64/libuuid.so.1` didn't work on arm64 openSUSE for me.)

So, I think the pragmatic fix is to:

- Copy the dependency list from app-builder to this project
- Change `libuuid` to `libuuid.so.1()(64bit)` in that list

**Comment by hovancik** [comment]
Maybe we should try open PR here? https://github.com/develar/app-builder/blob/4e2aa6a12e2bc3d31ec0d01d661fb3a4d65248ff/pkg/package-format/fpm/fpm.go#L156 

Would be best to fix this upstream, if possible. But honestly, this is beyond what I understand

**Comment by hovancik** [comment]
Deb has https://github.com/develar/app-builder/blob/4e2aa6a12e2bc3d31ec0d01d661fb3a4d65248ff/pkg/package-format/fpm/fpm.go#L148 `libuuid1`
