### ISSUE TITLE
[Bug]: Stretchly on Mac (Ventura M1) crashes right before starting break

### ISSUE THREAD

**Issue by acyment** [hovancik/stretchly#1267]
### Version

- [X] I'm using version 1.13.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.1

### Reproduction steps

The bug takes place right before a break is supposed to be triggered. I believe it started happening after updating to the latest version.

### Expected Behavior

A break, as usual

### Actual Behavior

I get the following screen:
![image](https://user-images.githubusercontent.com/1872616/215456360-9ccfc964-6dc4-4024-8021-f1a5077fd823.png)
Although the app seems to have crashed, I can still access a working menu at the tray bar.

### Relevant log output

```shell
[2023-01-29 21:37:36.058] [info]  System: resume or unlock
[2023-01-29 21:37:36.172] [info]  Stretchly: resuming breaks
[2023-01-29 21:37:41.651] [info]  System: resume or unlock
[2023-01-29 21:47:26.144] [error] TypeError: Object has been destroyed
    at showNotification (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1298:14)
    at startMicrobreakNotification (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:642:3)
    at BreaksPlanner.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:201:60)
    at BreaksPlanner.emit (node:events:513:28)
    at Timeout._onTimeout (/Applications/Stretchly.app/Contents/Resources/app.asar/breaksPlanner.js:145:53)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
[2023-01-29 22:16:06.029] [info]  System: suspend or lock
[2023-01-29 22:16:06.032] [info]  Stretchly: pausing breaks for 1ms
[2023-01-29 22:16:06.145] [info]  System: suspend or lock
[2023-01-29 22:16:06.146] [info]  Stretchly: not pausing for suspendOrLock because paused already
[2023-01-30 07:29:02.090] [info]  System: resume or unlock
[2023-01-30 07:29:02.092] [info]  Stretchly: resuming breaks
[2023-01-30 07:29:02.985] [info]  Stretchly: resuming breaks after idle time
[2023-01-30 07:29:04.827] [info]  System: resume or unlock
[2023-01-30 07:38:52.965] [error] TypeError: Object has been destroyed
    at showNotification (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1298:14)
    at startMicrobreakNotification (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:642:3)
    at BreaksPlanner.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:201:60)
    at BreaksPlanner.emit (node:events:513:28)
    at Timeout._onTimeout (/Applications/Stretchly.app/Contents/Resources/app.asar/breaksPlanner.js:145:53)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Looks like it's crashing on sending the notification: https://github.com/hovancik/stretchly/blob/78c31cf0b3011d165943ca6fb2aac90d00219122/app/main.js#L1298

I don't have mac m1 but will try on older mac I have

**Comment by acyment** [comment]
I realized that something weird is going on with the process associated with Stretchly. Here's a screenshot of the Battery section of the Activity Monitor (something similar appeared in the CPU section): 
![image](https://user-images.githubusercontent.com/1872616/216123462-27c1e16f-3fc9-46fa-a24f-346ca935b66a.png)

**Comment by hovancik** [comment]
What are the titles there? Can you check the number of items there when you start app and then later? 

It is possible that macOS kills the background window I use to send notifications and thus my attempt to notify fails. It would explain the error message.

**Comment by yuseferi** [comment]
same error for me toot "“Stretchly” is damaged and can’t be opened. You should move it to the Bin."

**Comment by acyment** [comment]
> same error for me toot "“Stretchly” is damaged and can’t be opened. You should move it to the Bin."

Hi yuseferi,

Your problem seems to be different. Take a look at this:
https://github.com/hovancik/stretchly#application-signing

**Comment by acyment** [comment]
> What are the titles there? Can you check the number of items there when you start app and then later?
> 
> It is possible that macOS kills the background window I use to send notifications and thus my attempt to notify fails. It would explain the error message.

It worked fine after rebooting 🤷🏻‍♂️

**Comment by hovancik** [comment]
okay, let's see if it ever happens again

**Comment by ntn-x2** [comment]
I can confirm that it keeps happening to me as well, on a Macbook Pro M1 with Ventura 13.1. Right before showing the break window. Plus, the first time the break window is shown, the icon appears in the Dock and there is no way to hide it again, while before it was not the case.

**Comment by hovancik** [comment]
@ntn-x2 dock icon has been fixed already and will be out with the new version :)
