### ISSUE TITLE
[Bug]: Stretchly won't quit properly, have to force quit instead

### ISSUE THREAD

**Issue by felipe-lee** [hovancik/stretchly#1316]
### Version

- [X] I'm using version 1.14.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.1

### Reproduction steps

I have been able to trigger this two ways, though it feels like they are likely the same issue.

#### How I came across the issue

1. Have stretchly open automatically when I log in.
2. Have a short break occur.
    1. To be honest, I haven't tested quitting the app after I log in and before a break occurs. I mainly put this step because of the other reproduction steps I have listed below.
3. Attempt to shut down my computer. 
    1. It fails to shut down because stretchly won't quit. I need to force quit in order to be able to then shut down.
 
#### Alternative to reproduce the issue without logging out/in

1. Open stretchly.
2. Skip to next mini break.
    1. If I only open stretchly, don't have a break, and try to close it, it closes just fine.
3. Postpone mini break.
5. Attempt to quit stretchly using "Quit Stretchly" button.
    ![image](https://user-images.githubusercontent.com/35938642/235806306-27a1ed9b-1d4b-4feb-a89b-c05418afbce7.png)
6. Nothing seems to happen, nor are there any logs related to quitting, but interestingly, if another break happens and I let it run through to the end, it just hangs and won't go back:
    ![image](https://user-images.githubusercontent.com/35938642/235807730-d6579efd-5931-43bb-8c82-0c86bca79c1f.png)
    1. This does produce a log error (`TypeError: Object has been destroyed`, details included in the log output section below), and I suspect it's because something did happen when I tried to quit (based on the `Object has been destroyed` error), but the quitting process didn't finish fully and so the app is still running but missing some of the things it needs. This is speculation on my part though 🤷🏼 

...
**Reproduces how often:** 100% so far.

### Expected Behavior

I would expect the app to quit cleanly without the need to force quit it.

### Actual Behavior

I have to force quit the app if I want to quit it. This is really mainly an issue for me when I'm trying to shut down my computer, because otherwise I usually leave stretchly running all day.

### Relevant log output

```shell
[2023-05-02 16:32:05.720] [info]  Stretchly: initializing...
[2023-05-02 16:32:05.729] [info]  Stretchly: loading preferences
[2023-05-02 16:32:05.740] [info]  Stretchly: starting Idle time monitoring
[2023-05-02 16:32:05.756] [info]  Stretchly: starting Do Not Disturb monitoring
[2023-05-02 16:32:05.849] [info]  Stretchly: loading default break ideas
[2023-05-02 16:32:05.902] [info]  Stretchly: loading default break ideas
[2023-05-02 16:32:09.647] [info]  Stretchly: skipping to Mini Break
[2023-05-02 16:32:10.053] [info]  Stretchly: showing window 1 of 2
[2023-05-02 16:32:10.074] [info]  Stretchly: starting Mini Break
[2023-05-02 16:32:10.165] [info]  Stretchly: showing window 2 of 2
[2023-05-02 16:32:11.387] [info]  Stretchly: postponing Mini Break
[2023-05-02 16:32:27.562] [info]  Stretchly: skipping to Mini Break
[2023-05-02 16:32:28.006] [info]  Stretchly: showing window 1 of 2
[2023-05-02 16:32:28.010] [info]  Stretchly: starting Mini Break
[2023-05-02 16:32:28.108] [info]  Stretchly: showing window 2 of 2
[2023-05-02 16:32:48.012] [error] TypeError: Object has been destroyed
    at breakComplete (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:945:16)
    at finishMicrobreak (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:955:20)
    at BreaksPlanner.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:209:80)
    at BreaksPlanner.emit (node:events:513:28)
    at Timeout._onTimeout (/Applications/Stretchly.app/Contents/Resources/app.asar/breaksPlanner.js:22:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

### Additional information

To be honest, I don't remember if it started when I upgraded to the latest version of the app, because I usually install updates to things at the start of my day and didn't notice this issue until I tried shutting down for the day, by which point I'd forgotten what updates I installed that morning.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Hi, sorry for late reply but super busy currently. I have some older mac so will try to reproduce there. Never had this issue on Linux so probably macOS related.

**Comment by hovancik** [comment]
I am on macOS 11.7.6, as I have older machine but can't reproduce. 

Error message suggests this line, but I don't see any reason why this window would not exist.

```
    processWin.webContents.send('playSound', settings.get(audio), settings.get('volume'))
```

The only rationale I see is when you first try quiting, some Stretchly processes are quit but not all of them. Can you check number of Stretchly processes before and after you try quit? 

<img width="950" alt="image" src="https://github.com/hovancik/stretchly/assets/4745859/ded43f25-f350-4b9a-be9e-6f5e2fed4fd2">

**Comment by felipe-lee** [comment]
No worries about the delay, I appreciate you making this app available at all.

It looks like there is a difference in the processes before and after quitting.

Before:
![image](https://github.com/hovancik/stretchly/assets/35938642/eb86ba17-c0af-4d1c-94ff-a592b0a17a44)

After:
![image](https://github.com/hovancik/stretchly/assets/35938642/ce25f37d-2d63-482d-b482-c901a950dbd3)

So, one of the instances of the "Strecthly Helper (Renderer)" processes gets closed, but every other process stays open.

**Comment by felipe-lee** [comment]
My screenshots from last time were after freshly opening Stretchly, but I was looking just now after having it running most of the day and there are a lot of processes running before I try to close it:

![image](https://github.com/hovancik/stretchly/assets/35938642/7c63fb9f-fed5-48ab-8ea3-2c4ff2366786)

After attempting to close it:

![image](https://github.com/hovancik/stretchly/assets/35938642/b9e35ef7-e050-4ffb-ad0e-69e861e302d1)

Only a few processes were ended. I wonder if this is why it won't close properly? Maybe there are more processes than expected and it's not finding them all.

**Comment by hovancik** [comment]
That's definetly bad behavior, the number of processes should stay the same (as when you start the app), with the difference in processes when break is on, or when preferences are opened. After they are closed, the number should go down again. Can you check when it seems to keep the processes for you? 

this is for me when I open the app

<img width="838" alt="Screenshot 2023-06-03 at 11 13 10" src="https://github.com/hovancik/stretchly/assets/4745859/25eac127-37e4-4013-8625-90b199af8320">

And after break

<img width="844" alt="Screenshot 2023-06-03 at 11 14 54" src="https://github.com/hovancik/stretchly/assets/4745859/eb078ae5-ec8b-4f5e-9e77-43458b9a7fa9">

What's weird the next break seems to work fine for me and I never go up more then 5 preferences.  

Closing Preferences seems to work fine.

**Comment by felipe-lee** [comment]
This is what I have right after opening it:

![image](https://github.com/hovancik/stretchly/assets/35938642/76fd10b5-f0cd-464c-a891-223378bb363f)

If I open preferences:

![image](https://github.com/hovancik/stretchly/assets/35938642/f6f753ef-d255-4b7b-9cf1-ee6220136a18)

And closing preferences (seems to end the process that had been added, so that seems to be working):

![image](https://github.com/hovancik/stretchly/assets/35938642/a5ef5467-6f47-4164-825e-2441ef27583e)

This is after a break (extra helper and "Renderer" processes):

![image](https://github.com/hovancik/stretchly/assets/35938642/a7f91c15-2174-4ee0-a472-891cacbe7759)

Another "Renderer" process is kept after each break it seems. Here are the processes after a second break:

![image](https://github.com/hovancik/stretchly/assets/35938642/1f34cecd-66cb-4178-b5a9-a212da1af188)

I started a break and skipped it and it also leaves behind a "Renderer" process:

![image](https://github.com/hovancik/stretchly/assets/35938642/b63af715-c397-48e1-a3f5-613e80b84e20)

**note**: Ignore the PID values. I fully quit and re-opened the app at one point because I had a few breaks go through and I wasn't sure if that affected things (kind of seems like it does), so I started over and worked to the same spot, just didn't take screenshots of the first steps again 😅

**Comment by felipe-lee** [comment]
I updated to 1.14.1 and now I don't have to force quit stretchly at the end of my day 🎉 

I do still have a bunch of extra processes (screenshot after having it open for 2-3 hours):

![image](https://github.com/hovancik/stretchly/assets/35938642/c3ca7799-484f-44ab-bb16-d48b54c7aa6b)

But at least now they all close when I shutdown my computer. I'm not sure if you want to keep this open for the extra processes, or if that should be a separate issue.

**Comment by asabaini** [comment]
I still have this issue on `1.14.1`

**Comment by huangxinjian** [comment]
I still have this issue on latest

**Comment by hovancik** [comment]
hi, still issue on latest 1.16? what macOS version?

**Comment by jhult** [comment]
Possibly related: https://github.com/hovancik/stretchly/issues/1604

**Comment by hovancik** [comment]
I am closing this as it is probably related to #1604 which will be released in next version.
