### ISSUE TITLE
[no bug] Crash with no explaination

### ISSUE THREAD

**Issue by fspade** [hovancik/stretchly#996]
### Version

- [X] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### Reproduction steps

I edited the config.json and Stretchly crashed. I compared the old and edited files and couldn't see a syntax error.
It works fine with the old file.
See attached my edited file ...
What am I missing?
[config.json.txt](https://github.com/hovancik/stretchly/files/6793834/config.json.txt)

### Expected Behavior

Stretchly running as usual.

### Actual Behavior

It crashes when the new file is in place.

### Relevant log output

```shell
[2021-07-09 22:23:19.445] [info]  Stretchly: initializing...
[2021-07-09 22:23:19.467] [info]  Stretchly: loading preferences
[2021-07-09 22:23:19.481] [info]  Stretchly: starting Idle time monitoring
[2021-07-09 22:28:37.139] [info]  Stretchly: initializing...
[2021-07-09 22:28:37.148] [error] SyntaxError: Unexpected token ] in JSON at position 4940
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (C:\Users\frank\AppData\Local\Programs\Stretchly\resources\app.asar\node_modules\conf\dist\source\index.js:69:43)
    at ElectronStore.get store [as store] (C:\Users\frank\AppData\Local\Programs\Stretchly\resources\app.asar\node_modules\conf\dist\source\index.js:278:43)
    at new Conf (C:\Users\frank\AppData\Local\Programs\Stretchly\resources\app.asar\node_modules\conf\dist\source\index.js:132:32)
    at new ElectronStore (C:\Users\frank\AppData\Local\Programs\Stretchly\resources\app.asar\node_modules\electron-store\index.js:69:3)
    at App.initialize (C:\Users\frank\AppData\Local\Programs\Stretchly\resources\app.asar\main.js:89:16)
    at App.emit (events.js:315:20)
```

### Preferences

```shell
{"spellcheck":{"dictionaries":["de"],"dictionary":""}}
```

### Additional information

```shell
I checked position 4940 (in line 201) and didn't see anything unusual.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment]
Please use some online tool, ie https://jsonformatter.org/ 

I am seeing: 

```
Parse error on line 204:
...nabled": true		},	],	"microbreakIdeas
---------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got ']'
```


there should not be `,` on 204
